export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Navbar } from './Navbar';
export { default as About } from './About';
export { default as Projects } from './Projects/index';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as ChatBot } from './ChatBot/index';
export { default as NeuralNexus } from '../games/neural-nexus/NeuralNexus';
